#!/usr/bin/env node
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// Generates C++ + Java FlatBuffers stubs from packages/native/schema/*.fbs
// using the flatc binary fetched by habitat (DEPS.py → shared/third_party/flatc).
//
// Runs automatically on `postinstall`, and manually via
// `pnpm --filter @lynx-skity/native generate-fbs` (re-run after editing the .fbs).
//
// Generates WITHOUT --gen-all: each header only defines its own types and
// #includes the others (guarded), so multiple stubs can be included together
// without redefinition errors. This mirrors lynx-native-svg's flatc usage.
import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const flatc = resolve(pkgRoot, "shared/third_party/flatc/flatc");
const schemaDir = resolve(pkgRoot, "schema");

if (!existsSync(flatc)) {
  console.warn("[lynx-skity] flatc not found at", flatc);
  console.warn(
    "[lynx-skity] Run `tools/hab sync` first, then `pnpm --filter @lynx-skity/native generate-fbs`.",
  );
  // Non-fatal: an install must not break just because habitat hasn't synced yet.
  process.exit(0);
}

const fbsFiles = ["render_tree_common.fbs", "render_tree_style.fbs", "render_tree.fbs"].map((f) =>
  resolve(schemaDir, f),
);

const cppOut = resolve(pkgRoot, "shared/skity/generated");
const javaOut = resolve(pkgRoot, "android/src/main/fbs-gen");
mkdirSync(cppOut, { recursive: true });
mkdirSync(javaOut, { recursive: true });

// flatc args shared by both backends (no --gen-all; see file header).
const flatcArgs = (lang, out) => [lang, "-o", out, "-I", schemaDir, ...fbsFiles];

console.log("[lynx-skity] generating C++ FlatBuffers stubs →", cppOut);
execFileSync(flatc, flatcArgs("--cpp", cppOut), { stdio: "inherit" });

console.log("[lynx-skity] generating Java FlatBuffers stubs →", javaOut);
// --java-package-prefix aligns the generated package with the rest of the
// Android code (com.skity.graphics.*); C++ stubs stay in namespace `skityrt`.
execFileSync(
  flatc,
  [
    "--java",
    "--java-package-prefix",
    "com.skity.graphics",
    "-o",
    javaOut,
    "-I",
    schemaDir,
    ...fbsFiles,
  ],
  { stdio: "inherit" },
);

// TypeScript stubs + vendored flatbuffers TS runtime → graphics/src/generated.
// The runtime is copied from the habitat-managed flatbuffers source so it stays
// the exact same version as flatc — a npm `flatbuffers` dependency would drift
// and silently break the stub↔runtime contract (the same reason Android / C++
// consume flatbuffers from source rather than a maven/npm artifact). Output is
// gitignored and regenerated by postinstall / generate-fbs, like C++ / Java.
const tsOut = resolve(pkgRoot, "../graphics/src/generated");
mkdirSync(tsOut, { recursive: true });

// 1) vendor the flatbuffers TS runtime (constants/types/utils/builder/...).
//    Excludes flexbuffers (parsers don't use it; it pulls a subdirectory we
//    don't copy). The runtime is third-party, so each file gets @ts-nocheck to
//    opt out of this project's strict / isolatedModules settings.
const fbTsSrc = resolve(pkgRoot, "shared/third_party/flatbuffers/ts");
const fbTsDst = resolve(tsOut, "flatbuffers");
rmSync(fbTsDst, { recursive: true, force: true });
mkdirSync(fbTsDst, { recursive: true });
for (const f of readdirSync(fbTsSrc)) {
  if (!f.endsWith(".ts") || f === "flexbuffers.ts") continue;
  const dst = resolve(fbTsDst, f);
  copyFileSync(resolve(fbTsSrc, f), dst);
  writeFileSync(dst, `// @ts-nocheck\n${readFileSync(dst, "utf8")}`);
}

// 2) generate the skityrt stubs.
console.log("[lynx-skity] generating TypeScript FlatBuffers stubs →", tsOut);
execFileSync(flatc, flatcArgs("--ts", tsOut), { stdio: "inherit" });

// 3) re-point stub imports from the "flatbuffers" package to the vendored runtime.
const stubDir = resolve(tsOut, "skityrt");
for (const f of readdirSync(stubDir)) {
  if (!f.endsWith(".ts")) continue;
  const p = resolve(stubDir, f);
  const rewritten = readFileSync(p, "utf8").replace(
    /from ['"]flatbuffers['"]/g,
    "from '../flatbuffers/flatbuffers.js'",
  );
  writeFileSync(p, rewritten);
}

console.log("[lynx-skity] FlatBuffers stubs generated.");
