// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ComputedStyle extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static ComputedStyle getRootAsComputedStyle(ByteBuffer _bb) { return getRootAsComputedStyle(_bb, new ComputedStyle()); }
  public static ComputedStyle getRootAsComputedStyle(ByteBuffer _bb, ComputedStyle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ComputedStyle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.skity.graphics.skityrt.ResolvedPaint fill() { return fill(new com.skity.graphics.skityrt.ResolvedPaint()); }
  public com.skity.graphics.skityrt.ResolvedPaint fill(com.skity.graphics.skityrt.ResolvedPaint obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.skity.graphics.skityrt.ResolvedPaint stroke() { return stroke(new com.skity.graphics.skityrt.ResolvedPaint()); }
  public com.skity.graphics.skityrt.ResolvedPaint stroke(com.skity.graphics.skityrt.ResolvedPaint obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public float strokeWidth() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f; }
  public byte strokeLinecap() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte strokeLinejoin() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public float strokeDasharray(int j) { int o = __offset(14); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int strokeDasharrayLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector strokeDasharrayVector() { return strokeDasharrayVector(new FloatVector()); }
  public FloatVector strokeDasharrayVector(FloatVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer strokeDasharrayAsByteBuffer() { return __vector_as_bytebuffer(14, 4); }
  public ByteBuffer strokeDasharrayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 4); }
  public float strokeDashoffset() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float strokeMiterlimit() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 4.0f; }
  public byte fillRule() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public float opacity() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f; }
  public byte display() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte visibility() { int o = __offset(26); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.skity.graphics.skityrt.TransformOp transform(int j) { return transform(new com.skity.graphics.skityrt.TransformOp(), j); }
  public com.skity.graphics.skityrt.TransformOp transform(com.skity.graphics.skityrt.TransformOp obj, int j) { int o = __offset(28); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int transformLength() { int o = __offset(28); return o != 0 ? __vector_len(o) : 0; }
  public com.skity.graphics.skityrt.TransformOp.Vector transformVector() { return transformVector(new com.skity.graphics.skityrt.TransformOp.Vector()); }
  public com.skity.graphics.skityrt.TransformOp.Vector transformVector(com.skity.graphics.skityrt.TransformOp.Vector obj) { int o = __offset(28); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createComputedStyle(FlatBufferBuilder builder,
      int fillOffset,
      int strokeOffset,
      float strokeWidth,
      byte strokeLinecap,
      byte strokeLinejoin,
      int strokeDasharrayOffset,
      float strokeDashoffset,
      float strokeMiterlimit,
      byte fillRule,
      float opacity,
      byte display,
      byte visibility,
      int transformOffset) {
    builder.startTable(13);
    ComputedStyle.addTransform(builder, transformOffset);
    ComputedStyle.addOpacity(builder, opacity);
    ComputedStyle.addStrokeMiterlimit(builder, strokeMiterlimit);
    ComputedStyle.addStrokeDashoffset(builder, strokeDashoffset);
    ComputedStyle.addStrokeDasharray(builder, strokeDasharrayOffset);
    ComputedStyle.addStrokeWidth(builder, strokeWidth);
    ComputedStyle.addStroke(builder, strokeOffset);
    ComputedStyle.addFill(builder, fillOffset);
    ComputedStyle.addVisibility(builder, visibility);
    ComputedStyle.addDisplay(builder, display);
    ComputedStyle.addFillRule(builder, fillRule);
    ComputedStyle.addStrokeLinejoin(builder, strokeLinejoin);
    ComputedStyle.addStrokeLinecap(builder, strokeLinecap);
    return ComputedStyle.endComputedStyle(builder);
  }

  public static void startComputedStyle(FlatBufferBuilder builder) { builder.startTable(13); }
  public static void addFill(FlatBufferBuilder builder, int fillOffset) { builder.addOffset(0, fillOffset, 0); }
  public static void addStroke(FlatBufferBuilder builder, int strokeOffset) { builder.addOffset(1, strokeOffset, 0); }
  public static void addStrokeWidth(FlatBufferBuilder builder, float strokeWidth) { builder.addFloat(2, strokeWidth, 1.0f); }
  public static void addStrokeLinecap(FlatBufferBuilder builder, byte strokeLinecap) { builder.addByte(3, strokeLinecap, 0); }
  public static void addStrokeLinejoin(FlatBufferBuilder builder, byte strokeLinejoin) { builder.addByte(4, strokeLinejoin, 0); }
  public static void addStrokeDasharray(FlatBufferBuilder builder, int strokeDasharrayOffset) { builder.addOffset(5, strokeDasharrayOffset, 0); }
  public static int createStrokeDasharrayVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startStrokeDasharrayVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addStrokeDashoffset(FlatBufferBuilder builder, float strokeDashoffset) { builder.addFloat(6, strokeDashoffset, 0.0f); }
  public static void addStrokeMiterlimit(FlatBufferBuilder builder, float strokeMiterlimit) { builder.addFloat(7, strokeMiterlimit, 4.0f); }
  public static void addFillRule(FlatBufferBuilder builder, byte fillRule) { builder.addByte(8, fillRule, 0); }
  public static void addOpacity(FlatBufferBuilder builder, float opacity) { builder.addFloat(9, opacity, 1.0f); }
  public static void addDisplay(FlatBufferBuilder builder, byte display) { builder.addByte(10, display, 0); }
  public static void addVisibility(FlatBufferBuilder builder, byte visibility) { builder.addByte(11, visibility, 0); }
  public static void addTransform(FlatBufferBuilder builder, int transformOffset) { builder.addOffset(12, transformOffset, 0); }
  public static int createTransformVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTransformVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endComputedStyle(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ComputedStyle get(int j) { return get(new ComputedStyle(), j); }
    public ComputedStyle get(ComputedStyle obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

