// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class Display {
  private Display() { }
  public static final byte INLINE = 0;
  public static final byte NONE = 1;

  public static final String[] names = { "INLINE", "NONE", };

  public static String name(int e) { return names[e]; }
}

