// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class FillRule {
  private FillRule() { }
  public static final byte NONZERO = 0;
  public static final byte EVENODD = 1;

  public static final String[] names = { "NONZERO", "EVENODD", };

  public static String name(int e) { return names[e]; }
}

