// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Gradient extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static Gradient getRootAsGradient(ByteBuffer _bb) { return getRootAsGradient(_bb, new Gradient()); }
  public static Gradient getRootAsGradient(ByteBuffer _bb, Gradient obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Gradient __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte gradientUnits() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte spreadMethod() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public float x1() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float y1() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float x2() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f; }
  public float y2() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float cx() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.5f; }
  public float cy() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.5f; }
  public float r() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.5f; }
  public float fx() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.5f; }
  public float fy() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.5f; }
  public float fr() { int o = __offset(28); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public com.skity.graphics.skityrt.GradientStop stops(int j) { return stops(new com.skity.graphics.skityrt.GradientStop(), j); }
  public com.skity.graphics.skityrt.GradientStop stops(com.skity.graphics.skityrt.GradientStop obj, int j) { int o = __offset(30); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int stopsLength() { int o = __offset(30); return o != 0 ? __vector_len(o) : 0; }
  public com.skity.graphics.skityrt.GradientStop.Vector stopsVector() { return stopsVector(new com.skity.graphics.skityrt.GradientStop.Vector()); }
  public com.skity.graphics.skityrt.GradientStop.Vector stopsVector(com.skity.graphics.skityrt.GradientStop.Vector obj) { int o = __offset(30); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createGradient(FlatBufferBuilder builder,
      byte type,
      byte gradientUnits,
      byte spreadMethod,
      float x1,
      float y1,
      float x2,
      float y2,
      float cx,
      float cy,
      float r,
      float fx,
      float fy,
      float fr,
      int stopsOffset) {
    builder.startTable(14);
    Gradient.addStops(builder, stopsOffset);
    Gradient.addFr(builder, fr);
    Gradient.addFy(builder, fy);
    Gradient.addFx(builder, fx);
    Gradient.addR(builder, r);
    Gradient.addCy(builder, cy);
    Gradient.addCx(builder, cx);
    Gradient.addY2(builder, y2);
    Gradient.addX2(builder, x2);
    Gradient.addY1(builder, y1);
    Gradient.addX1(builder, x1);
    Gradient.addSpreadMethod(builder, spreadMethod);
    Gradient.addGradientUnits(builder, gradientUnits);
    Gradient.addType(builder, type);
    return Gradient.endGradient(builder);
  }

  public static void startGradient(FlatBufferBuilder builder) { builder.startTable(14); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addGradientUnits(FlatBufferBuilder builder, byte gradientUnits) { builder.addByte(1, gradientUnits, 0); }
  public static void addSpreadMethod(FlatBufferBuilder builder, byte spreadMethod) { builder.addByte(2, spreadMethod, 0); }
  public static void addX1(FlatBufferBuilder builder, float x1) { builder.addFloat(3, x1, 0.0f); }
  public static void addY1(FlatBufferBuilder builder, float y1) { builder.addFloat(4, y1, 0.0f); }
  public static void addX2(FlatBufferBuilder builder, float x2) { builder.addFloat(5, x2, 1.0f); }
  public static void addY2(FlatBufferBuilder builder, float y2) { builder.addFloat(6, y2, 0.0f); }
  public static void addCx(FlatBufferBuilder builder, float cx) { builder.addFloat(7, cx, 0.5f); }
  public static void addCy(FlatBufferBuilder builder, float cy) { builder.addFloat(8, cy, 0.5f); }
  public static void addR(FlatBufferBuilder builder, float r) { builder.addFloat(9, r, 0.5f); }
  public static void addFx(FlatBufferBuilder builder, float fx) { builder.addFloat(10, fx, 0.5f); }
  public static void addFy(FlatBufferBuilder builder, float fy) { builder.addFloat(11, fy, 0.5f); }
  public static void addFr(FlatBufferBuilder builder, float fr) { builder.addFloat(12, fr, 0.0f); }
  public static void addStops(FlatBufferBuilder builder, int stopsOffset) { builder.addOffset(13, stopsOffset, 0); }
  public static int createStopsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStopsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGradient(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Gradient get(int j) { return get(new Gradient(), j); }
    public Gradient get(Gradient obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

