// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GradientStop extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static GradientStop getRootAsGradientStop(ByteBuffer _bb) { return getRootAsGradientStop(_bb, new GradientStop()); }
  public static GradientStop getRootAsGradientStop(ByteBuffer _bb, GradientStop obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GradientStop __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float offset() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public com.skity.graphics.skityrt.RGBAColor color() { return color(new com.skity.graphics.skityrt.RGBAColor()); }
  public com.skity.graphics.skityrt.RGBAColor color(com.skity.graphics.skityrt.RGBAColor obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createGradientStop(FlatBufferBuilder builder,
      float offset,
      int colorOffset) {
    builder.startTable(2);
    GradientStop.addColor(builder, colorOffset);
    GradientStop.addOffset(builder, offset);
    return GradientStop.endGradientStop(builder);
  }

  public static void startGradientStop(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addOffset(FlatBufferBuilder builder, float offset) { builder.addFloat(0, offset, 0.0f); }
  public static void addColor(FlatBufferBuilder builder, int colorOffset) { builder.addOffset(1, colorOffset, 0); }
  public static int endGradientStop(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GradientStop get(int j) { return get(new GradientStop(), j); }
    public GradientStop get(GradientStop obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

