// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class GradientUnits {
  private GradientUnits() { }
  public static final byte OBJECT_BOUNDING_BOX = 0;
  public static final byte USER_SPACE_ON_USE = 1;

  public static final String[] names = { "OBJECT_BOUNDING_BOX", "USER_SPACE_ON_USE", };

  public static String name(int e) { return names[e]; }
}

