// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class LineCap {
  private LineCap() { }
  public static final byte BUTT = 0;
  public static final byte ROUND = 1;
  public static final byte SQUARE = 2;

  public static final String[] names = { "BUTT", "ROUND", "SQUARE", };

  public static String name(int e) { return names[e]; }
}

