// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class LineJoin {
  private LineJoin() { }
  public static final byte MITER = 0;
  public static final byte ROUND = 1;
  public static final byte BEVEL = 2;

  public static final String[] names = { "MITER", "ROUND", "BEVEL", };

  public static String name(int e) { return names[e]; }
}

