// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class PathCommandType {
  private PathCommandType() { }
  public static final byte MOVE_TO = 0;
  public static final byte LINE_TO = 1;
  public static final byte CUBIC_TO = 2;
  public static final byte QUAD_TO = 3;
  public static final byte ARC_TO = 4;
  public static final byte CLOSE = 5;

  public static final String[] names = { "MOVE_TO", "LINE_TO", "CUBIC_TO", "QUAD_TO", "ARC_TO", "CLOSE", };

  public static String name(int e) { return names[e]; }
}

