// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RenderNode extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static RenderNode getRootAsRenderNode(ByteBuffer _bb) { return getRootAsRenderNode(_bb, new RenderNode()); }
  public static RenderNode getRootAsRenderNode(ByteBuffer _bb, RenderNode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RenderNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public String tagName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tagNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tagNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public com.skity.graphics.skityrt.ComputedStyle style() { return style(new com.skity.graphics.skityrt.ComputedStyle()); }
  public com.skity.graphics.skityrt.ComputedStyle style(com.skity.graphics.skityrt.ComputedStyle obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public float x() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float y() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float width() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float height() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float cx() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float cy() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float r() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float rx() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float ry() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float x1() { int o = __offset(28); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float y1() { int o = __offset(30); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float x2() { int o = __offset(32); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float y2() { int o = __offset(34); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float offset() { int o = __offset(36); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public com.skity.graphics.skityrt.RenderNode children(int j) { return children(new com.skity.graphics.skityrt.RenderNode(), j); }
  public com.skity.graphics.skityrt.RenderNode children(com.skity.graphics.skityrt.RenderNode obj, int j) { int o = __offset(38); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int childrenLength() { int o = __offset(38); return o != 0 ? __vector_len(o) : 0; }
  public com.skity.graphics.skityrt.RenderNode.Vector childrenVector() { return childrenVector(new com.skity.graphics.skityrt.RenderNode.Vector()); }
  public com.skity.graphics.skityrt.RenderNode.Vector childrenVector(com.skity.graphics.skityrt.RenderNode.Vector obj) { int o = __offset(38); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public com.skity.graphics.skityrt.PathCommand pathCommands(int j) { return pathCommands(new com.skity.graphics.skityrt.PathCommand(), j); }
  public com.skity.graphics.skityrt.PathCommand pathCommands(com.skity.graphics.skityrt.PathCommand obj, int j) { int o = __offset(40); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int pathCommandsLength() { int o = __offset(40); return o != 0 ? __vector_len(o) : 0; }
  public com.skity.graphics.skityrt.PathCommand.Vector pathCommandsVector() { return pathCommandsVector(new com.skity.graphics.skityrt.PathCommand.Vector()); }
  public com.skity.graphics.skityrt.PathCommand.Vector pathCommandsVector(com.skity.graphics.skityrt.PathCommand.Vector obj) { int o = __offset(40); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public float points(int j) { int o = __offset(42); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int pointsLength() { int o = __offset(42); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector pointsVector() { return pointsVector(new FloatVector()); }
  public FloatVector pointsVector(FloatVector obj) { int o = __offset(42); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer pointsAsByteBuffer() { return __vector_as_bytebuffer(42, 4); }
  public ByteBuffer pointsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 42, 4); }
  public byte gradientUnits() { int o = __offset(44); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte spreadMethod() { int o = __offset(46); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createRenderNode(FlatBufferBuilder builder,
      int id,
      int tagNameOffset,
      int styleOffset,
      float x,
      float y,
      float width,
      float height,
      float cx,
      float cy,
      float r,
      float rx,
      float ry,
      float x1,
      float y1,
      float x2,
      float y2,
      float offset,
      int childrenOffset,
      int pathCommandsOffset,
      int pointsOffset,
      byte gradientUnits,
      byte spreadMethod) {
    builder.startTable(22);
    RenderNode.addPoints(builder, pointsOffset);
    RenderNode.addPathCommands(builder, pathCommandsOffset);
    RenderNode.addChildren(builder, childrenOffset);
    RenderNode.addOffset(builder, offset);
    RenderNode.addY2(builder, y2);
    RenderNode.addX2(builder, x2);
    RenderNode.addY1(builder, y1);
    RenderNode.addX1(builder, x1);
    RenderNode.addRy(builder, ry);
    RenderNode.addRx(builder, rx);
    RenderNode.addR(builder, r);
    RenderNode.addCy(builder, cy);
    RenderNode.addCx(builder, cx);
    RenderNode.addHeight(builder, height);
    RenderNode.addWidth(builder, width);
    RenderNode.addY(builder, y);
    RenderNode.addX(builder, x);
    RenderNode.addStyle(builder, styleOffset);
    RenderNode.addTagName(builder, tagNameOffset);
    RenderNode.addId(builder, id);
    RenderNode.addSpreadMethod(builder, spreadMethod);
    RenderNode.addGradientUnits(builder, gradientUnits);
    return RenderNode.endRenderNode(builder);
  }

  public static void startRenderNode(FlatBufferBuilder builder) { builder.startTable(22); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, -1); }
  public static void addTagName(FlatBufferBuilder builder, int tagNameOffset) { builder.addOffset(1, tagNameOffset, 0); }
  public static void addStyle(FlatBufferBuilder builder, int styleOffset) { builder.addOffset(2, styleOffset, 0); }
  public static void addX(FlatBufferBuilder builder, float x) { builder.addFloat(3, x, 0.0f); }
  public static void addY(FlatBufferBuilder builder, float y) { builder.addFloat(4, y, 0.0f); }
  public static void addWidth(FlatBufferBuilder builder, float width) { builder.addFloat(5, width, 0.0f); }
  public static void addHeight(FlatBufferBuilder builder, float height) { builder.addFloat(6, height, 0.0f); }
  public static void addCx(FlatBufferBuilder builder, float cx) { builder.addFloat(7, cx, 0.0f); }
  public static void addCy(FlatBufferBuilder builder, float cy) { builder.addFloat(8, cy, 0.0f); }
  public static void addR(FlatBufferBuilder builder, float r) { builder.addFloat(9, r, 0.0f); }
  public static void addRx(FlatBufferBuilder builder, float rx) { builder.addFloat(10, rx, 0.0f); }
  public static void addRy(FlatBufferBuilder builder, float ry) { builder.addFloat(11, ry, 0.0f); }
  public static void addX1(FlatBufferBuilder builder, float x1) { builder.addFloat(12, x1, 0.0f); }
  public static void addY1(FlatBufferBuilder builder, float y1) { builder.addFloat(13, y1, 0.0f); }
  public static void addX2(FlatBufferBuilder builder, float x2) { builder.addFloat(14, x2, 0.0f); }
  public static void addY2(FlatBufferBuilder builder, float y2) { builder.addFloat(15, y2, 0.0f); }
  public static void addOffset(FlatBufferBuilder builder, float offset) { builder.addFloat(16, offset, 0.0f); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(17, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPathCommands(FlatBufferBuilder builder, int pathCommandsOffset) { builder.addOffset(18, pathCommandsOffset, 0); }
  public static int createPathCommandsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPathCommandsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPoints(FlatBufferBuilder builder, int pointsOffset) { builder.addOffset(19, pointsOffset, 0); }
  public static int createPointsVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startPointsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGradientUnits(FlatBufferBuilder builder, byte gradientUnits) { builder.addByte(20, gradientUnits, 0); }
  public static void addSpreadMethod(FlatBufferBuilder builder, byte spreadMethod) { builder.addByte(21, spreadMethod, 0); }
  public static int endRenderNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RenderNode get(int j) { return get(new RenderNode(), j); }
    public RenderNode get(RenderNode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

