// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ResolvedPaint extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static ResolvedPaint getRootAsResolvedPaint(ByteBuffer _bb) { return getRootAsResolvedPaint(_bb, new ResolvedPaint()); }
  public static ResolvedPaint getRootAsResolvedPaint(ByteBuffer _bb, ResolvedPaint obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ResolvedPaint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.skity.graphics.skityrt.RGBAColor color() { return color(new com.skity.graphics.skityrt.RGBAColor()); }
  public com.skity.graphics.skityrt.RGBAColor color(com.skity.graphics.skityrt.RGBAColor obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.skity.graphics.skityrt.Gradient gradient() { return gradient(new com.skity.graphics.skityrt.Gradient()); }
  public com.skity.graphics.skityrt.Gradient gradient(com.skity.graphics.skityrt.Gradient obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createResolvedPaint(FlatBufferBuilder builder,
      byte type,
      int colorOffset,
      int gradientOffset) {
    builder.startTable(3);
    ResolvedPaint.addGradient(builder, gradientOffset);
    ResolvedPaint.addColor(builder, colorOffset);
    ResolvedPaint.addType(builder, type);
    return ResolvedPaint.endResolvedPaint(builder);
  }

  public static void startResolvedPaint(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addColor(FlatBufferBuilder builder, int colorOffset) { builder.addOffset(1, colorOffset, 0); }
  public static void addGradient(FlatBufferBuilder builder, int gradientOffset) { builder.addOffset(2, gradientOffset, 0); }
  public static int endResolvedPaint(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ResolvedPaint get(int j) { return get(new ResolvedPaint(), j); }
    public ResolvedPaint get(ResolvedPaint obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

