// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RGBAColor extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static RGBAColor getRootAsRGBAColor(ByteBuffer _bb) { return getRootAsRGBAColor(_bb, new RGBAColor()); }
  public static RGBAColor getRootAsRGBAColor(ByteBuffer _bb, RGBAColor obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RGBAColor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long r() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long g() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long b() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long a() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 255L; }

  public static int createRGBAColor(FlatBufferBuilder builder,
      long r,
      long g,
      long b,
      long a) {
    builder.startTable(4);
    RGBAColor.addA(builder, a);
    RGBAColor.addB(builder, b);
    RGBAColor.addG(builder, g);
    RGBAColor.addR(builder, r);
    return RGBAColor.endRGBAColor(builder);
  }

  public static void startRGBAColor(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addR(FlatBufferBuilder builder, long r) { builder.addInt(0, (int) r, (int) 0L); }
  public static void addG(FlatBufferBuilder builder, long g) { builder.addInt(1, (int) g, (int) 0L); }
  public static void addB(FlatBufferBuilder builder, long b) { builder.addInt(2, (int) b, (int) 0L); }
  public static void addA(FlatBufferBuilder builder, long a) { builder.addInt(3, (int) a, (int) 255L); }
  public static int endRGBAColor(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RGBAColor get(int j) { return get(new RGBAColor(), j); }
    public RGBAColor get(RGBAColor obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

