// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class SpreadMethod {
  private SpreadMethod() { }
  public static final byte PAD = 0;
  public static final byte REFLECT = 1;
  public static final byte REPEAT = 2;

  public static final String[] names = { "PAD", "REFLECT", "REPEAT", };

  public static String name(int e) { return names[e]; }
}

