// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class TransformType {
  private TransformType() { }
  public static final byte MATRIX = 0;
  public static final byte TRANSLATE = 1;
  public static final byte SCALE = 2;
  public static final byte ROTATE = 3;
  public static final byte SKEW_X = 4;
  public static final byte SKEW_Y = 5;

  public static final String[] names = { "MATRIX", "TRANSLATE", "SCALE", "ROTATE", "SKEW_X", "SKEW_Y", };

  public static String name(int e) { return names[e]; }
}

