// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TransformOp extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_12_19(); }
  public static TransformOp getRootAsTransformOp(ByteBuffer _bb) { return getRootAsTransformOp(_bb, new TransformOp()); }
  public static TransformOp getRootAsTransformOp(ByteBuffer _bb, TransformOp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TransformOp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public float args(int j) { int o = __offset(6); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int argsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector argsVector() { return argsVector(new FloatVector()); }
  public FloatVector argsVector(FloatVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer argsAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer argsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createTransformOp(FlatBufferBuilder builder,
      byte type,
      int argsOffset) {
    builder.startTable(2);
    TransformOp.addArgs(builder, argsOffset);
    TransformOp.addType(builder, type);
    return TransformOp.endTransformOp(builder);
  }

  public static void startTransformOp(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addArgs(FlatBufferBuilder builder, int argsOffset) { builder.addOffset(1, argsOffset, 0); }
  public static int createArgsVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startArgsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTransformOp(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TransformOp get(int j) { return get(new TransformOp(), j); }
    public TransformOp get(TransformOp obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

