// automatically generated by the FlatBuffers compiler, do not modify

package com.skity.graphics.skityrt;

@SuppressWarnings("unused")
public final class Visibility {
  private Visibility() { }
  public static final byte VISIBLE = 0;
  public static final byte HIDDEN = 1;

  public static final String[] names = { "VISIBLE", "HIDDEN", };

  public static String name(int e) { return names[e]; }
}

