// Generated by @lynx-js/autolink-codegen. Edit the method bodies as needed.
#include "napi.h"

#ifdef USE_WEAK_SUFFIX_NAPI
#include "weak_napi_defines.h"
#endif

#ifdef LYNX_LIBRARY_USE_PRIMJS_NAPI_MODULE
typedef struct lynx_autolink_napi_module {
  int nm_version;
  const char *nm_filename;
  napi_addon_register_func nm_register_func;
  const char *nm_modname;
  struct lynx_autolink_napi_module *nm_link;
} lynx_autolink_napi_module;

extern "C" void napi_module_register_xx(lynx_autolink_napi_module *mod);

#undef NAPI_MODULE
#define NAPI_MODULE(modname, regfunc)                                                              \
  EXTERN_C_START                                                                                   \
  static lynx_autolink_napi_module _module_##modname = {NAPI_MODULE_VERSION, __FILE__, regfunc,    \
                                                        #modname, nullptr};                        \
  void _napi_register_xx_##modname(void) __attribute__((constructor));                             \
  void _napi_register_xx_##modname(void) { napi_module_register_xx(&_module_##modname); }          \
  EXTERN_C_END
#endif

namespace {

void Check(napi_env env, napi_status status) {
  if (status != napi_ok) {
    napi_throw_error(env, nullptr, "N-API call failed");
  }
}

void SetFunction(napi_env env, napi_value object, const char *name, napi_callback callback) {
  napi_value function;
  Check(env, napi_create_function(env, name, NAPI_AUTO_LENGTH, callback, nullptr, &function));
  Check(env, napi_set_named_property(env, object, name, function));
}

Napi::Value SetValue(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   setValue(
  //     key: string,
  //     value: string,
  //   ): void
  // types/napi-native-module.d.ts:6
  if (info.Length() < 2) {
    return env.Undefined();
  }
  // Param: key: string
  // types/napi-native-module.d.ts:6
  Napi::String key = info[0].As<Napi::String>();
  (void)key;
  // Param: value: string
  // types/napi-native-module.d.ts:6
  Napi::String value = info[1].As<Napi::String>();
  (void)value;
  return env.Undefined();
}

Napi::Value GetValue(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   getValue(
  //     key: string,
  //   ): string | null
  // types/napi-native-module.d.ts:7
  if (info.Length() < 1) {
    return env.Undefined();
  }
  // Param: key: string
  // types/napi-native-module.d.ts:7
  Napi::String key = info[0].As<Napi::String>();
  (void)key;
  return env.Null();
}

Napi::Value SetArray(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   setArray(
  //     value: Array<number>,
  //   ): void
  // types/napi-native-module.d.ts:8
  if (info.Length() < 1) {
    return env.Undefined();
  }
  // Param: value: Array<number>
  // types/napi-native-module.d.ts:8
  Napi::Array value = info[0].As<Napi::Array>();
  (void)value;
  return env.Undefined();
}

Napi::Value SetNumber(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   setNumber(
  //     value: number,
  //   ): void
  // types/napi-native-module.d.ts:9
  if (info.Length() < 1) {
    return env.Undefined();
  }
  // Param: value: number
  // types/napi-native-module.d.ts:9
  Napi::Number value = info[0].As<Napi::Number>();
  (void)value;
  return env.Undefined();
}

Napi::Value Clear(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   clear(): void
  // types/napi-native-module.d.ts:10
  return env.Undefined();
}

Napi::Value CreateColorFilter(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   createColorFilter(): Object
  // types/napi-native-module.d.ts:12
  return Napi::Object::New(env);
}

Napi::Value CreateShader(const Napi::CallbackInfo &info) {
  Napi::Env env = info.Env();
  // Method:
  //   createShader(): Object
  // types/napi-native-module.d.ts:13
  return Napi::Object::New(env);
}

napi_value SetValueCallback(napi_env env, napi_callback_info info) {
  return SetValue(Napi::CallbackInfo(env, info));
}

napi_value GetValueCallback(napi_env env, napi_callback_info info) {
  return GetValue(Napi::CallbackInfo(env, info));
}

napi_value SetArrayCallback(napi_env env, napi_callback_info info) {
  return SetArray(Napi::CallbackInfo(env, info));
}

napi_value SetNumberCallback(napi_env env, napi_callback_info info) {
  return SetNumber(Napi::CallbackInfo(env, info));
}

napi_value ClearCallback(napi_env env, napi_callback_info info) {
  return Clear(Napi::CallbackInfo(env, info));
}

napi_value CreateColorFilterCallback(napi_env env, napi_callback_info info) {
  return CreateColorFilter(Napi::CallbackInfo(env, info));
}

napi_value CreateShaderCallback(napi_env env, napi_callback_info info) {
  return CreateShader(Napi::CallbackInfo(env, info));
}

void BindScumbleModule(napi_env env, napi_value exports) {
  SetFunction(env, exports, "setValue", SetValueCallback);
  SetFunction(env, exports, "getValue", GetValueCallback);
  SetFunction(env, exports, "setArray", SetArrayCallback);
  SetFunction(env, exports, "setNumber", SetNumberCallback);
  SetFunction(env, exports, "clear", ClearCallback);
  SetFunction(env, exports, "createColorFilter", CreateColorFilterCallback);
  SetFunction(env, exports, "createShader", CreateShaderCallback);
}

static napi_value CreateScumbleModule(napi_env env, napi_value exports) {
  BindScumbleModule(env, exports);
  return exports;
}

} // namespace

extern "C" napi_value LynxAutolinkCreateScumbleModule(napi_env env, napi_value exports,
                                                        const char *module_name, void *opaque) {
  (void)module_name;
  (void)opaque;
  return CreateScumbleModule(env, exports);
}

// Standard Node-API addon entry point. The host's NAPI addon loader
// (Explorer-style: liblynx_napi_addon_loader.so) dlopen's this addon and
// dlsym's this symbol to initialize it with a real napi_env. On the primjs
// NAPI path the NAPI_MODULE macro below is used instead; both coexist.
extern "C" __attribute__((visibility("default"))) napi_value
napi_register_module_v1(napi_env env, napi_value exports) {
  return CreateScumbleModule(env, exports);
}

#ifdef LYNX_LIBRARY_USE_PRIMJS_NAPI_MODULE
NAPI_MODULE(ScumbleModule, CreateScumbleModule)
#endif

#ifdef USE_WEAK_SUFFIX_NAPI
#include "weak_napi_undefs.h"
#endif
